/* Commonly used character constants */
#define SPACE ' '
#define NEWLINE '\n'
#define COMMA ','
#define SEMICOLON ';'
#define LEFT_PAREN '('
#define RIGHT_PAREN ')'
#define LEFT_BRACKET '['
#define RIGHT_BRACKET ']'
#define LEFT_BRACE '{'
#define RIGHT_BRACE '}'
#define PLUS '+'
#define MINUS '-' 
#define MULTIPLY '*'
#define DIVIDE '/'
#define BITAND '&'
#define BITOR '|'
#define MODULUS '%'
#define EQUAL '='
#define QUESTION_MARK '?'
#define COLON ':'
#define LESS_THAN '<'
#define LARGER_THAN '>'
#define NOT '!'
#define BIT_COMPLEMENT '~'
#define FORTRAN_COMMENT_CHAR 'C'
