C#########################################################
C This file is part of OpenAD released under the LGPL.   #
C The full COPYRIGHT notice can be found in the top      #
C level directory of the OpenAD distribution             #
C#########################################################
C
C$OPENAD XXX File_start [head.f]
      SUBROUTINE head(X, Y)
          use OAD_tape
          use OAD_rev
          use OAD_cp

C original arguments get inserted before version
C         ! and declared here together with all local variables
C         ! generated by xaifBooster

      use OAD_active
      use w2f__types
      use oad_intrinsics
      use oad_intrinsics
      use oad_intrinsics
      IMPLICIT NONE
C
C     **** Parameters and Result ****
C
      type(active) :: X(1:2)
      type(active) :: Y(1:2)
C
C     **** Local Variables and Functions ****
C
      type(active) :: Z(1:INT(SIZE(X)))
      INTEGER(w2f__i8) OpenAD_Symbol_0
      INTEGER(w2f__i8) OpenAD_Symbol_1
      INTEGER(w2f__i8) OpenAD_Symbol_10
      INTEGER(w2f__i8) OpenAD_Symbol_2
      REAL(w2f__8) OpenAD_Symbol_3(1 : 2)
      REAL(w2f__8) OpenAD_Symbol_4(1 : 2)
      REAL(w2f__8) OpenAD_Symbol_5(1 : 2)
      INTEGER(w2f__i8) OpenAD_Symbol_6
      REAL(w2f__8) OpenAD_Symbol_7(1 : 2)
      REAL(w2f__8) OpenAD_Symbol_8(1 : 2)
      INTEGER(w2f__i8) OpenAD_Symbol_9
      REAL(w2f__8) OpenAD_acc_0(1 : 2)
      REAL(w2f__8) OpenAD_acc_1(1 : 2)
      REAL(w2f__8) OpenAD_acc_2(1 : 2)
      REAL(w2f__8) OpenAD_aux_0(1 : 2)
      REAL(w2f__8) OpenAD_aux_1(1 : 2)
      REAL(w2f__8) OpenAD_lin_0(1 : 2)
      REAL(w2f__8) OpenAD_lin_1(:)
      ALLOCATABLE OpenAD_lin_1
      REAL(w2f__8) OpenAD_lin_2(1 : 2)
      REAL(w2f__8) OpenAD_lin_3(1 : 2)
      REAL(w2f__8) OpenAD_lin_4(1 : 2)
      REAL(w2f__8) OpenAD_lin_5(:)
      ALLOCATABLE OpenAD_lin_5
      REAL(w2f__8) OpenAD_lin_6(1 : 2)
      type(active) :: OpenAD_prp_0(1:2)
C
C     **** Top Level Pragmas ****
C
C$OPENAD INDEPENDENT(X)
C$OPENAD DEPENDENT(Y)
C
C     **** Statements ****
C


C checkpointing stacks and offsets
          integer :: cp_loop_variable_1,cp_loop_variable_2,cp_loop_varia
     +ble_3,cp_loop_variable_4,cp_loop_variable_5,cp_loop_variable_6

C floats 'F'
          double precision, dimension(:), allocatable, save :: theArgFSt
     +ack
          integer, save :: theArgFStackoffset=0, theArgFStackSize=0
C integers 'I'
          integer, dimension(:), allocatable, save :: theArgIStack
          integer, save :: theArgIStackoffset=0, theArgIStackSize=0
C booleans 'B'
          logical, dimension(:), allocatable, save :: theArgBStack
          integer, save :: theArgBStackoffset=0, theArgBStackSize=0
C strings 'S'
          character*(80), dimension(:), allocatable, save :: theArgSStac
     +k
          integer, save :: theArgSStackoffset=0, theArgSStackSize=0

          type(modeType) :: our_orig_mode

C external C function used in inlined code
          integer iaddr
          external iaddr
C$OPENAD XXX Template ad_template.f
C$OPENAD XXX Template ad_template.f

          if (our_rev_mode%arg_store) then
C store arguments
          end if
          if (our_rev_mode%arg_restore) then
C restore arguments
          end if
          if (our_rev_mode%plain) then
            our_orig_mode=our_rev_mode
            our_rev_mode%arg_store=.FALSE.
C original function
      Z(1:INT(SIZE(X)))%v = X(1:2)%v
      Y(1:2)%v = (Z(1:INT(SIZE(X)))%v*COS(X%v))
      Y(1:2)%v = ((X(1:2)%v*Z(1:INT(SIZE(X)))%v)/Y(1:2)%v)

C original function end
            our_rev_mode=our_orig_mode
          end if
          if (our_rev_mode%tape) then
C            print*, " tape       ", our_rev_mode
            our_rev_mode%arg_store=.TRUE.
            our_rev_mode%arg_restore=.FALSE.
            our_rev_mode%plain=.TRUE.
            our_rev_mode%tape=.FALSE.
            our_rev_mode%adjoint=.FALSE.
C taping
      Z(1:INT(SIZE(X)))%v = X(1:2)%v
      OpenAD_Symbol_0 = SIZE(X)
      integer_tape(integer_tape_pointer) = OpenAD_Symbol_0
      integer_tape_pointer = integer_tape_pointer+1
      OpenAD_aux_0 = COS(X%v)
      OpenAD_lin_0 = OpenAD_aux_0
      OpenAD_lin_2 = (-SIN(X%v))
C!! requested inline of 'oad_AllocateMatching' has no defn
      CALL oad_AllocateMatching(OpenAD_lin_1,Z(1:INT(SIZE(X))))
      OpenAD_lin_1 = Z(1:INT(SIZE(X)))%v
      Y(1:2)%v = (Z(1:INT(SIZE(X)))%v*OpenAD_aux_0)
      OpenAD_acc_0 = (OpenAD_lin_2*OpenAD_lin_1)
      double_tape(double_tape_pointer:double_tape_pointer+size(OpenAD_li
     +n_0,1)-1) = OpenAD_lin_0(:)
      double_tape_pointer = double_tape_pointer+size(OpenAD_lin_0,1)
      OpenAD_Symbol_1 = SIZE(X)
      integer_tape(integer_tape_pointer) = OpenAD_Symbol_1
      integer_tape_pointer = integer_tape_pointer+1
      double_tape(double_tape_pointer:double_tape_pointer+size(OpenAD_ac
     +c_0,1)-1) = OpenAD_acc_0(:)
      double_tape_pointer = double_tape_pointer+size(OpenAD_acc_0,1)
      OpenAD_aux_1 = (X(1:2)%v*Z(1:INT(SIZE(X)))%v)
C!! requested inline of 'oad_AllocateMatching' has no defn
      CALL oad_AllocateMatching(OpenAD_lin_5,Z(1:INT(SIZE(X))))
      OpenAD_lin_5 = Z(1:INT(SIZE(X)))%v
      OpenAD_lin_6 = X(1:2)%v
      OpenAD_lin_3 = (INT(1_w2f__i8)/Y(1:2)%v)
      OpenAD_lin_4 = (-(OpenAD_aux_1/(Y(1:2)%v*Y(1:2)%v)))
      Y(1:2)%v = (OpenAD_aux_1/Y(1:2)%v)
      OpenAD_acc_1 = (OpenAD_lin_5*OpenAD_lin_3)
      OpenAD_acc_2 = (OpenAD_lin_6*OpenAD_lin_3)
      double_tape(double_tape_pointer:double_tape_pointer+size(OpenAD_li
     +n_4,1)-1) = OpenAD_lin_4(:)
      double_tape_pointer = double_tape_pointer+size(OpenAD_lin_4,1)
      double_tape(double_tape_pointer:double_tape_pointer+size(OpenAD_ac
     +c_1,1)-1) = OpenAD_acc_1(:)
      double_tape_pointer = double_tape_pointer+size(OpenAD_acc_1,1)
      double_tape(double_tape_pointer:double_tape_pointer+size(OpenAD_ac
     +c_2,1)-1) = OpenAD_acc_2(:)
      double_tape_pointer = double_tape_pointer+size(OpenAD_acc_2,1)
      OpenAD_Symbol_2 = SIZE(X)
      integer_tape(integer_tape_pointer) = OpenAD_Symbol_2
      integer_tape_pointer = integer_tape_pointer+1

C taping end
            our_rev_mode%arg_store=.FALSE.
            our_rev_mode%arg_restore=.FALSE.
            our_rev_mode%plain=.FALSE.
            our_rev_mode%tape=.FALSE.
            our_rev_mode%adjoint=.TRUE.
          end if
          if (our_rev_mode%adjoint) then
C            print*, " adjoint    ", our_rev_mode
            our_rev_mode%arg_store=.FALSE.
            our_rev_mode%arg_restore=.TRUE.
            our_rev_mode%plain=.FALSE.
            our_rev_mode%tape=.TRUE.
            our_rev_mode%adjoint=.FALSE.
C adjoint
      double_tape_pointer = double_tape_pointer-size(OpenAD_Symbol_3,1)
      OpenAD_Symbol_3(:) = double_tape(double_tape_pointer:double_tape_p
     +ointer+size(OpenAD_Symbol_3,1)-1)
      double_tape_pointer = double_tape_pointer-size(OpenAD_Symbol_4,1)
      OpenAD_Symbol_4(:) = double_tape(double_tape_pointer:double_tape_p
     +ointer+size(OpenAD_Symbol_4,1)-1)
      double_tape_pointer = double_tape_pointer-size(OpenAD_Symbol_5,1)
      OpenAD_Symbol_5(:) = double_tape(double_tape_pointer:double_tape_p
     +ointer+size(OpenAD_Symbol_5,1)-1)
      integer_tape_pointer = integer_tape_pointer-1
      OpenAD_Symbol_6 = integer_tape(integer_tape_pointer)
      Z(1:INT(OpenAD_Symbol_6))%d = Z(1:INT(OpenAD_Symbol_6))%d+Y(1:2)%d
     +*(OpenAD_Symbol_3)
      X(1:2)%d = X(1:2)%d+Y(1:2)%d*(OpenAD_Symbol_4)
      OpenAD_prp_0%d = OpenAD_prp_0%d+Y(1:2)%d*(OpenAD_Symbol_5)
      Y(1:2)%d = 0.0d0
      Y(1:2)%d = Y(1:2)%d+OpenAD_prp_0%d
      OpenAD_prp_0%d = 0.0d0
      double_tape_pointer = double_tape_pointer-size(OpenAD_Symbol_7,1)
      OpenAD_Symbol_7(:) = double_tape(double_tape_pointer:double_tape_p
     +ointer+size(OpenAD_Symbol_7,1)-1)
      double_tape_pointer = double_tape_pointer-size(OpenAD_Symbol_8,1)
      OpenAD_Symbol_8(:) = double_tape(double_tape_pointer:double_tape_p
     +ointer+size(OpenAD_Symbol_8,1)-1)
      X%d = X%d+Y(1:2)%d*(OpenAD_Symbol_7)
      integer_tape_pointer = integer_tape_pointer-1
      OpenAD_Symbol_9 = integer_tape(integer_tape_pointer)
      Z(1:INT(OpenAD_Symbol_9))%d = Z(1:INT(OpenAD_Symbol_9))%d+Y(1:2)%d
     +*(OpenAD_Symbol_8)
      Y(1:2)%d = 0.0d0
      integer_tape_pointer = integer_tape_pointer-1
      OpenAD_Symbol_10 = integer_tape(integer_tape_pointer)
      X(1:2)%d = X(1:2)%d+Z(1:INT(OpenAD_Symbol_10))%d
      Z(1:INT(OpenAD_Symbol_10))%d = 0.0d0

C adjoint end
            our_rev_mode%arg_store=.FALSE.
            our_rev_mode%arg_restore=.TRUE.
            our_rev_mode%plain=.FALSE.
            our_rev_mode%tape=.TRUE.
            our_rev_mode%adjoint=.FALSE.
          end if
        end subroutine head
