# ========== begin copyright notice ===================
# This file is part of
# ---------------
# xaifBooster
# ---------------
# which is distributed under the BSD license.
# The full COPYRIGHT notice can be found in the top
# level directory of the xaifBooster distribution.
# ========== end copyright notice =====================
# default target
default: objs

include ../../../Makefile.incl
-include $(DEPINCL)

objs: obj $(OBJS)

.PHONY: objs driver 
