C#########################################################
C This file is part of OpenAD released under the LGPL.   #
C The full COPYRIGHT notice can be found in the top      #
C level directory of the OpenAD distribution             #
C#########################################################
        SUBROUTINE OpenAD_MASKER(N,M,THCK)
          use OAD_tape
          use OAD_rev

C original arguments get inserted before version
C         ! and declared here together with all local variables
C         ! generated by xaifBooster

        use OAD_active
        INTEGER N
        INTEGER M
        REAL THCK(1 : N, 1 : M)
        INTEGER I=2
        INTEGER J=2


          integer iaddr
          external iaddr
            if (oad_dt_sz.lt.oad_dt_ptr+(size(THCK(I+(-1):I+1,J+(-1):J+1
     +),1)*size(THCK(I+(-1):I+1,J+(-1):J+1),2))) call oad_dt_grow()
            oad_dt(oad_dt_ptr:) = reshape(THCK(I+(-1):I+1,J+(-1):J+1),(/
     +size(THCK(I+(-1):I+1,J+(-1):J+1),1)*size(THCK(I+(-1):I+1,J+(-1):J+
     +1),2)/))
            oad_dt_ptr = oad_dt_ptr+(size(THCK(I+(-1):I+1,J+(-1):J+1),1)
     +*size(THCK(I+(-1):I+1,J+(-1):J+1),2))

         if (our_rev_mode%plain) then
C original function
          end if
          if (our_rev_mode%tape) then
C taping
          end if
          if (our_rev_mode%adjoint) then
C adjoint
          end if
        end subroutine OpenAD_MASKER
