# ========== begin copyright notice ===================
# This file is part of
# ---------------
# xaifBooster
# ---------------
# which is distributed under the BSD license.
# The full COPYRIGHT notice can be found in the top
# level directory of the xaifBooster distribution.
# ========== end copyright notice =====================
objs driver clean:
	cd CrossCountryInterface && $(MAKE) $@
	cd InlinableXMLRepresentation && $(MAKE) $@
	cd SaveValuesAcross && $(MAKE) $@
	cd CodeReplacement && $(MAKE) $@
	cd DerivativePropagator && $(MAKE) $@
	cd RequiredValues && $(MAKE) $@
	cd AdjointUtils && $(MAKE) $@
	cd TypeChange && $(MAKE) $@
	cd Linearization && $(MAKE) $@
	cd BasicBlockPreaccumulation && $(MAKE) $@
	cd BasicBlockPreaccumulationTape && $(MAKE) $@
	cd BasicBlockPreaccumulationTapeAdjoint && $(MAKE) $@
	cd ControlFlowReversal && $(MAKE) $@
	cd TraceDiff && $(MAKE) $@
	cd AddressArithmetic && $(MAKE) $@
	cd PushPop && $(MAKE) $@
	cd BasicBlockPreaccumulationReverse && $(MAKE) $@

.PHONY: objs driver clean
